### ISSUE TITLE
How to include NOT rules

### ISSUE THREAD

**Issue by v15a1** [alvesoaj/eFLL#35]
As you know Fuzzy logic translates Linguistic rules into logical rules that can include AND, OR, NOT operators. Although eFLL has `joinWithAND`, `joinSingle` and `joinWithOR`, I can't seem to find a method for NOT. Taking the example sketches, how may I include the rule:
```
Distance is Near AND speed is NOT Fast
```
?

**Comment by alvesoaj** [comment]
Hello, there is no not rule... sincerely, I don't know about the not rule in Fuzzy, may be this technic was improved since last time I used it. May you share any paper to help me get updated?
