### ISSUE TITLE
Does it work on Stm32F4 ? 

### ISSUE THREAD

**Issue by auditore2208** [alvesoaj/eFLL#36]
Hello AJ Alves.I want answer a question to you about your eFLL library.I have an stm microcontroller (STM32F429I DISCOVERY Board ) and i want do a project with fuzzy logic. Can i use your eFLL library using STMCube ide on this board for fuzzy logic projects ?

**Comment by cdudzek** [comment]
This code should work with any standard C++ compiler. I know it has been used on other STM32 controllers with IAR Workbench. Just add the code files to your project, and you can follow the examples for using the library.

**Comment by alvesoaj** [comment]
Thanks @cdudzek
